### ISSUE TITLE
试了一下发现两个问题

### ISSUE THREAD

**Issue by auhah** [yaming116/UpdateApp#1]
1. 不支持https
2. 下载时候会疯狂的提示新Notification

**Comment by yaming116** [comment]
疯狂的提示新的notification是什么意思？

**Comment by auhah** [comment]
进度更新一下, 提示音就响一次, 手机是魅蓝note2

**Comment by yaming116** [comment]
了解，你可以提交一个修复或等晚上我更新一下

**Comment by yaming116** [comment]
现在下载notification 的解决就是把声音去掉，但是@13120241790  想把声音变成配置项，这个大家有什么好的建议？

**Comment by 13120241790** [comment]
回复这么及时 真是敬业 👍

**Comment by yaming116** [comment]
@auhah @13120241790 第一个问题已经修复的，https还需要好好考虑一下怎么处理比较好

**Comment by yaming116** [comment]
@auhah 这个我先关闭了，https的我新开了一个 #3 ，需要讨论一下
