### ISSUE TITLE
我已经用v4 的替代了 

### ISSUE THREAD

**Issue by 13120241790** [yaming116/UpdateApp#11]
目前没发现什么问题 可用。 谢谢 UPDATE_NUMBER_SIZE 您也可以在源码里面改大一点， 20kb 就通知一次 手机基本上会特别卡顿   最后谢谢你无私的奉献

**Comment by yaming116** [comment]
这个参数你可以调节的，现在是下载进度没增加1%更新一下

**Comment by 13120241790** [comment]
嗯呢  知道了 谢谢大拿

**Comment by 13120241790** [comment]
<string name="update_app_model_progress">正在下载 %d&#160;%</string>

大拿  通知栏上面的进度 加 % 号 可加吗？ 目前我这样加了  通知栏就一直是准备下载的状态

**Comment by 13120241790** [comment]
`<string name="update_app_model_progress">正在下载 %d&#160;%</string>`

**Comment by yaming116** [comment]
啥？

**Comment by yaming116** [comment]
默认是有进度的%的呀，你是怎么产生的？

**Comment by 13120241790** [comment]
现在就是正在下载 后面数字在变动 但是 没有 % 号 我自己在 string.xml 文件里面加 % 号 就不行

**Comment by yaming116** [comment]
%，在string 里面是特殊字符，你把你的截图给我看一下？我现在测试都是好的

**Comment by 13120241790** [comment]
一会去我去试试转义好使不 ，  我先去截图 但是 github 传图可能很慢  上次传图一直在 uploading 大拿有邮箱没 我发你邮件

**Comment by 13120241790** [comment]
可能是 github 的服务器在国外的原因 图片确实传不上去

**Comment by 13120241790** [comment]
图片发您 163 网易邮箱里面了

**Comment by yaming116** [comment]
@13120241790 你好，我看了一下邮件没有新信息，还有你可以把项目下载下来试试sample是不是产生一样的效果

**Comment by 13120241790** [comment]
下了   也 run 起来了 也是一样的 ， 通知栏 进度下面的数字 是没有 %  号的 
我发的是 yaming116@163.com 这个邮箱

**Comment by yaming116** [comment]
@13120241790 兄弟呀，我的邮箱没有反应，垃圾箱也看了，你发送到我gmail吧，yaming1106@gmail.com

**Comment by 13120241790** [comment]
gmail 也发了 你看看收到了吗

**Comment by yaming116** [comment]
@13120241790 你确定发送成功了？为什么我两个都没有反应？

**Comment by 13120241790** [comment]
晕 真心发送成功了 你QQ多少  方便加你 QQ 吗？

**Comment by yaming116** [comment]
434715737

**Comment by 13120241790** [comment]
大拿 加了 麻烦通过以下
