### ISSUE TITLE
怎么联系作者啊

### ISSUE THREAD

**Issue by VliceZ** [yaming116/UpdateApp#15]

**Comment by VliceZ** [comment]
可以加作者的QQ吗？

**Comment by yaming116** [comment]
有什么问题吗？

**Comment by VliceZ** [comment]
很抱歉打扰你了，但是有些使用上的问题希望能指导一下。。。

**Comment by yaming116** [comment]
有问题直接建立一个问题好了，也可以帮助后来使用的人

**Comment by VliceZ** [comment]
没有太详细的使用说明啊，我复制UpdateService.Builder.create(url).build(context);这一段代码  Builder是红的

**Comment by yaming116** [comment]
请按照说明，添加gradle依赖

**Comment by VliceZ** [comment]
添加了

**Comment by VliceZ** [comment]
allprojects {
    repositories {
        maven { url "https://www.jitpack.io" }
    }
}

dependencies {
    compile 'com.github.yaming116:UpdateApp:1.0.3'
}都添加了  Builder还是报红

**Comment by yaming116** [comment]
你可以试试demo项目，添加依赖过后，查看你的依赖有没有下载下来，..\build\intermediates\exploded-aar，里面

**Comment by VliceZ** [comment]
demo有下载链接吗

**Comment by yaming116** [comment]
github有提供啊，当前项目源代码
