### ISSUE TITLE
安装没有适配7.0吗？

### ISSUE THREAD

**Issue by yhbuao** [yaming116/UpdateApp#17]
android.os.FileUriExposedException:

**Comment by yaming116** [comment]
能提供一下详细信息吗？

**Comment by antoniodisanto92** [comment]
Add this in Application Class:

StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
StrictMode.setVmPolicy(builder.build());

**Comment by crook3** [comment]
确实是不兼容7.0，看这篇文章解决方法，希望楼主尽快解决。http://www.jianshu.com/p/577816c3ce93

**Comment by yaming116** [comment]
大家有没有好的建议控制动态文件夹，如果按照7.0的要求需要注册制定文件夹，下载参数用来指定文件夹可能就不能用了

**Comment by crook3** [comment]
https://github.com/WVector/AppUpdate
你可以参考他的做法，兼容了7.0，但是我觉得你的更简单易用，我更喜欢，除了不兼容7.0以外。

**Comment by yaming116** [comment]
最新修复代码已经提交，依赖还没有更新

**Comment by lxxc** [comment]
大神您好！我在用华为的Android7.0进行真机测试的时候发现了两个问题。
1.通知栏显示下载100%的时候，没有自动弹出安装界面，一直卡在100%，点击该通知也没用。
2.在下载过程中，如果再次触发版本更新，会多出一个通知先，一直卡在刚开始。这样就有多个通知栏。
本人是Android小白，如果是哪里用的不对，还望大神多多指教。
       顺颂商祺！

**Comment by yaming116** [comment]
源码是兼容的7.0，远程依赖还没有更新，多次更新得我明天看下

**Comment by PeanutZhang** [comment]
请问7.0远程依赖现在好了没

**Comment by yaming116** [comment]
周末更新

**Comment by PeanutZhang** [comment]
安装后，安装包还在，再次下载的时候，就不会在下载新的安装包了，这样的话下次更新的时候会不会出现这样的情况，检测到已经存在的安装包，是不是就直接安装旧的包，导致不会下载新的安装包了呢？

**Comment by yaming116** [comment]
已经更新 SNAPSHOT，一个月之内没有问题，发布Release
