### ISSUE TITLE
如何添加UpdateProgressListener，显示自定义ProgressBar UI?

### ISSUE THREAD

**Issue by zouxianbincc** [yaming116/UpdateApp#24]
/**
     * Class used for the client Binder.
     */
    public class LocalBinder extends Binder {
        /**
         * set update progress call back
         *
         * @param listener
         */
        public void setUpdateProgressListener(UpdateProgressListener listener) {
            UpdateService.this.setUpdateProgressListener(listener);
        }
    }

**Comment by yaming116** [comment]
这个不支持自定义，如果需要可以自己fork 修改。
