### ISSUE TITLE
NotificationCompat

### ISSUE THREAD

**Issue by 13120241790** [yaming116/UpdateApp#8]
您好 ， NotificationCompat 在 v7 版本 22 以下是没有的 这个问题有办法可以解决吗？ 或者用别的方法替代

**Comment by yaming116** [comment]
@13120241790  不能升级吗？这个可以用v4的替代，我当初开源码两个有一点点差别，v7的新增加了一些支持，如果不可以升级，这个需要想想有没有别的方法，或者我把v7的集成到项目中

**Comment by yaming116** [comment]
@13120241790 你好，我现在把这个换回到 v4 NotificationCompat,他新加的特性我没有用到，谢谢你的反馈

**Comment by yaming116** [comment]
#9 ,请升级到最新版本
